version: "3"

services:
  shopwaredb:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=shopware
    volumes:
     - dbvolume:/var/lib/mysql

  shopware:
    image: mspittka/shopware
    volumes:
     - webvolume:/var/www/html
     - ./config/apache-site.conf:/etc/apache2/sites-available/000-default.conf
     - ./log/apache2:/var/log/apache2
     - ./log/build:/var/log/build
     - ./config/build.sh:/build.sh
    links:
     - shopwaredb:db
    ports:
     - "80:80"
     - "443:443"

  shopwaressh:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
     - "24:22"
    volumes:
     - dbvolume:/root/dbvolume
     - webvolume:/root/webvolume

volumes:
   webvolume:
   dbvolume: