version: "3"

services:
  shopwaredb:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=shopware
    volumes:
     - dbvolume:/var/lib/mysql

  shopware:
    image: mspittka/shopware
    environment:
     - SHOPWAREBUILD_GIT_REPO=https://github.com/shopware/shopware.git
     - SHOPWAREBUILD_DB_HOST=db
     - SHOPWAREBUILD_DB_NAME=shopware
     - SHOPWAREBUILD_DB_USER=root
     - SHOPWAREBUILD_DB_PASSWORD=shopware
     - SHOPWAREBUILD_DB_PORT=3306
     - SHOPWAREBUILD_APP_PATH=
     - SHOPWAREBUILD_APP_HOST=shopwaredemo.in
     - SHOPWAREBUILD_ANT_TARGET=build-unit
     - SHOPWAREBUILD_DEMO_ZIP=http://releases.s3.shopware.com/test_images.zip
    volumes:
     - webvolume:/var/www/html
     - ./config/apache-site.conf:/etc/apache2/sites-available/000-default.conf
     - ./log/apache2:/var/log/apache2
    links:
     - shopwaredb:db
    ports:
     - "80:80"
     - "443:443"
     - "9000:9000"

  shopwaressh:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
     - "24:22"
    volumes:
     - dbvolume:/root/dbvolume
     - webvolume:/root/webvolume
   
volumes:
   webvolume:
   dbvolume: